spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: true
  datasource:
    url: jdbc:h2:mem:securitydemo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: securitydemo
    password: securitydemo
    generate-unique-name: true
    driver-class-name: org.h2.Driver

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:8181/auth/realms/securitydemo/protocol/openid-connect/certs
      id: securitydemo-backend

server:
  port: 8080
