spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/auth/realms/security-demo
          jwk-set-uri: http://keycloak:8080/auth/realms/security-demo/protocol/openid-connect/certs
